/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCoronillaRouteImport } from './routes/_authenticated/coronilla'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiasRouteImport } from './routes/_authenticated/dias'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AudiosIndexRouteImport } from './routes/audios.index'
import { Route as AudiosDayNumberRouteImport } from './routes/audios.$dayNumber'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthenticatedDiaIndexRouteImport } from './routes/_authenticated/dia.index'
import { Route as AuthenticatedDiaDayNumberRouteImport } from './routes/_authenticated/dia.$dayNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoronillaRoute = AuthenticatedCoronillaRouteImport.update({
  id: '/coronilla',
  path: '/coronilla',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiasRoute = AuthenticatedDiasRouteImport.update({
  id: '/dias',
  path: '/dias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AudiosIndexRoute = AudiosIndexRouteImport.update({
  id: '/audios/',
  path: '/audios/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiosDayNumberRoute = AudiosDayNumberRouteImport.update({
  id: '/audios/$dayNumber',
  path: '/audios/$dayNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDiaIndexRoute = AuthenticatedDiaIndexRouteImport.update({
  id: '/dia/',
  path: '/dia/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiaDayNumberRoute =
  AuthenticatedDiaDayNumberRouteImport.update({
    id: '/dia/$dayNumber',
    path: '/dia/$dayNumber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/recursos': typeof RecursosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/coronilla': typeof AuthenticatedCoronillaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dias': typeof AuthenticatedDiasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/audios/$dayNumber': typeof AudiosDayNumberRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/audios/': typeof AudiosIndexRoute
  '/dia/$dayNumber': typeof AuthenticatedDiaDayNumberRoute
  '/dia/': typeof AuthenticatedDiaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/recursos': typeof RecursosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/coronilla': typeof AuthenticatedCoronillaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dias': typeof AuthenticatedDiasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/audios/$dayNumber': typeof AudiosDayNumberRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/audios': typeof AudiosIndexRoute
  '/dia/$dayNumber': typeof AuthenticatedDiaDayNumberRoute
  '/dia': typeof AuthenticatedDiaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/recursos': typeof RecursosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/coronilla': typeof AuthenticatedCoronillaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dias': typeof AuthenticatedDiasRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/audios/$dayNumber': typeof AudiosDayNumberRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/audios/': typeof AudiosIndexRoute
  '/_authenticated/dia/$dayNumber': typeof AuthenticatedDiaDayNumberRoute
  '/_authenticated/dia/': typeof AuthenticatedDiaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/recursos'
    | '/admin'
    | '/coronilla'
    | '/dashboard'
    | '/dias'
    | '/onboarding'
    | '/perfil'
    | '/audios/$dayNumber'
    | '/auth/reset-password'
    | '/audios/'
    | '/dia/$dayNumber'
    | '/dia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/recursos'
    | '/admin'
    | '/coronilla'
    | '/dashboard'
    | '/dias'
    | '/onboarding'
    | '/perfil'
    | '/audios/$dayNumber'
    | '/auth/reset-password'
    | '/audios'
    | '/dia/$dayNumber'
    | '/dia'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/recursos'
    | '/_authenticated/admin'
    | '/_authenticated/coronilla'
    | '/_authenticated/dashboard'
    | '/_authenticated/dias'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/audios/$dayNumber'
    | '/auth/reset-password'
    | '/audios/'
    | '/_authenticated/dia/$dayNumber'
    | '/_authenticated/dia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  RecursosRoute: typeof RecursosRoute
  AudiosDayNumberRoute: typeof AudiosDayNumberRoute
  AudiosIndexRoute: typeof AudiosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coronilla': {
      id: '/_authenticated/coronilla'
      path: '/coronilla'
      fullPath: '/coronilla'
      preLoaderRoute: typeof AuthenticatedCoronillaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dias': {
      id: '/_authenticated/dias'
      path: '/dias'
      fullPath: '/dias'
      preLoaderRoute: typeof AuthenticatedDiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/audios/': {
      id: '/audios/'
      path: '/audios'
      fullPath: '/audios/'
      preLoaderRoute: typeof AudiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audios/$dayNumber': {
      id: '/audios/$dayNumber'
      path: '/audios/$dayNumber'
      fullPath: '/audios/$dayNumber'
      preLoaderRoute: typeof AudiosDayNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dia/': {
      id: '/_authenticated/dia/'
      path: '/dia'
      fullPath: '/dia/'
      preLoaderRoute: typeof AuthenticatedDiaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dia/$dayNumber': {
      id: '/_authenticated/dia/$dayNumber'
      path: '/dia/$dayNumber'
      fullPath: '/dia/$dayNumber'
      preLoaderRoute: typeof AuthenticatedDiaDayNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCoronillaRoute: typeof AuthenticatedCoronillaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiasRoute: typeof AuthenticatedDiasRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedDiaDayNumberRoute: typeof AuthenticatedDiaDayNumberRoute
  AuthenticatedDiaIndexRoute: typeof AuthenticatedDiaIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCoronillaRoute: AuthenticatedCoronillaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiasRoute: AuthenticatedDiasRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedDiaDayNumberRoute: AuthenticatedDiaDayNumberRoute,
  AuthenticatedDiaIndexRoute: AuthenticatedDiaIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  RecursosRoute: RecursosRoute,
  AudiosDayNumberRoute: AudiosDayNumberRoute,
  AudiosIndexRoute: AudiosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
