create table if not exists public.super_admins(user_id uuid primary key references auth.users(id) on delete cascade,created_at timestamptz not null default now());
insert into public.super_admins(user_id) select id from auth.users where lower(email)=lower('lavozdejesusco@gmail.com') on conflict do nothing;
alter table public.super_admins enable row level security;
grant select on public.super_admins to authenticated; grant all on public.super_admins to service_role;
create or replace function public.is_super_admin(candidate uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.super_admins where user_id=candidate)$$;
revoke all on function public.is_super_admin(uuid) from public,anon; grant execute on function public.is_super_admin(uuid) to authenticated;
create policy "super admin reads own marker" on public.super_admins for select to authenticated using(user_id=(select auth.uid()));
create policy "admins read profiles" on public.profiles for select to authenticated using((select public.has_role((select auth.uid()),'admin')));
create policy "admins update profiles" on public.profiles for update to authenticated using((select public.has_role((select auth.uid()),'admin'))) with check((select public.has_role((select auth.uid()),'admin')));
create policy "admins read enrollments" on public.user_consecrations for select to authenticated using((select public.has_role((select auth.uid()),'admin')));
create policy "admins update enrollments" on public.user_consecrations for update to authenticated using((select public.has_role((select auth.uid()),'admin'))) with check((select public.has_role((select auth.uid()),'admin')));
create policy "admins read progress" on public.user_day_progress for select to authenticated using((select public.has_role((select auth.uid()),'admin')));
create policy "admins read roles" on public.user_roles for select to authenticated using((select public.has_role((select auth.uid()),'admin')));
create or replace function public.super_admin_set_user_role(target_user uuid,next_role public.app_role) returns void language plpgsql security definer set search_path=public as $$begin if not public.is_super_admin(auth.uid()) then raise exception 'Only the super administrator can change roles';end if;if target_user=auth.uid() and next_role<>'admin' then raise exception 'Cannot remove the super administrator';end if;delete from public.user_roles where user_id=target_user and role<>'user';insert into public.user_roles(user_id,role) values(target_user,next_role) on conflict do nothing;end;$$;
revoke all on function public.super_admin_set_user_role(uuid,public.app_role) from public,anon; grant execute on function public.super_admin_set_user_role(uuid,public.app_role) to authenticated;
create table if not exists public.audit_logs(id uuid primary key default gen_random_uuid(),actor_id uuid references auth.users(id) on delete set null,action text not null,entity_type text not null,entity_id uuid,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.audit_logs enable row level security; grant select,insert on public.audit_logs to authenticated; grant all on public.audit_logs to service_role;
create policy "admins read audit" on public.audit_logs for select to authenticated using((select public.has_role((select auth.uid()),'admin')));
create policy "staff write audit" on public.audit_logs for insert to authenticated with check((select auth.uid())=actor_id and ((select public.has_role((select auth.uid()),'admin')) or (select public.has_role((select auth.uid()),'editor'))));
create index if not exists audit_logs_created_idx on public.audit_logs(created_at desc);
create index if not exists enrollments_admin_idx on public.user_consecrations(consecration_id,status,updated_at desc);
create index if not exists progress_admin_idx on public.user_day_progress(user_consecration_id,completed,updated_at desc);
